AWSTemplateFormatVersion: '2010-09-09'
Description: Zero Spend Budget Notification using SNS and Lambda

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address to receive budget notifications

Resources:

  ZeroSpendSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ZeroSpendBudgetTopic

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref ZeroSpendSNSTopic

  BudgetNotificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BudgetNotificationLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  BudgetNotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BudgetNotificationHandler
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt BudgetNotificationLambdaRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print("Received budget alert event:")
              print(event)
              return {
                  'statusCode': 200,
                  'body': 'Budget notification processed.'
              }

  BudgetNotificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BudgetNotificationFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref ZeroSpendSNSTopic

  BudgetNotificationSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt BudgetNotificationFunction.Arn
      TopicArn: !Ref ZeroSpendSNSTopic

  ZeroSpendBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: ZeroSpendBudget
        BudgetLimit:
          Amount: 0.01
          Unit: USD
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref ZeroSpendSNSTopic
